### ISSUE TITLE
[1,2,3].at('last') returns what?

### ISSUE THREAD

**Issue by zeldajay** [tc39/proposal-relative-indexing-method#40]

**Comment by nicolo-ribaudo** [comment]
Possible cause for the question 😛: https://twitter.com/haxy/status/1351404633088954368?s=20

Answer: similarly to many other array methods, this one converts it's parameter to an integer. `"last"` first becomes NaN, which then becomes 0. (spec: https://tc39.es/ecma262/#sec-tointeger).
Thus, when passing `last` you get the first character, similarly to when you pass any other non-numeric string.

**Comment by styfle** [comment]
Why was it coerced to an integer? Is that silent failure favorable over throwing an error?

**Comment by ljharb** [comment]
That's the convention/idiom followed by the vast majority of built-in methods - coerce arguments to the expected type.

**Comment by septs** [comment]
i think need bounds checking

1. assert input value type, e.g: https://tc39.es/ecma262/#sec-isfinite-number
2. checking domain of input value, e.g: `[-length, length]`

Reference: https://en.wikipedia.org/wiki/Interval_(mathematics)

**Comment by hax** [comment]
The behavior is *understandable*, but not *reasonable*. The motivation is give programmers a better `a[index]` but actually give a worse one:

- `a['not-an-index']` normally give u `undefined`, `a.at('not-an-index')` give u the first one.
- `a[1n]` same as `a[1]`, `a.at(1n)` throw.

**Comment by syg** [comment]
Closing this for now; I feel strongly that this behavior isn't up for debate. The current behavior is consistent with other builtins like `slice`.

It is a non-goal to align `o.at(expr)` with `o[expr]`.

**Comment by Becavalier** [comment]
I would prefer the behavior should be consistent with the `[]`. And since this is a new feature, I do not think it will take too much effort to get it done. Even though like what @ljharb said, it's the convention to make it align with other build-in methods, but what is the most important part is the real use case of this method,  returning `undefined` should be better for the end developers in this case and this is exactly what they expected.

**Comment by nicolo-ribaudo** [comment]
> but what is the most important part is the real use case of this method

It's a method to get array elements based on (positive or negative) indexes, there isn't a real use case passing a string as an argument imho.

It's an edge case that will almost never happen in practice, and as such we should strive for consistency so that people don't have to learn a new exception in the language behaviour.
