### ISSUE TITLE
Get the last array element with array destructuring syntax

### ISSUE THREAD

**Issue by MiroslavPetrik** [tc39/proposal-relative-indexing-method#54]
The one real use case is `.at(-1)` being `.last()`.

Given we have array Destructuring , why not extend it so it mimics the mighty `coffeescript`?

```coffeescript
[..., last] = [0,1,2,3]

console.info({last}) # last: 3
```

```coffeescript
[first, ...gather, , last] = [0,1,2,3]

console.info({first, gather, last})

# first: 0
# gather: [1]
# mid - 2 - is omitted
# last: 3
```

**Comment by tabatkins** [comment]
That's been rejected as part of destructuring in the past, because there's no clear answer for what to do when the source array is too short. In your example, if the source array was just `[0]`, `gather` clearly should be empty, but are `first` and `last` both `0`? Or does one "win" the claim while the other is `undefined`?

Similarly, consider:

```js
[...heads, tail1, tail2] = [0]
```

Again, `heads` is obviously empty, but is `tail1` undefined and `tail2` 0? Or the other way around?

Due to these questions and the lack of any obvious answer, we've never specced destructuring-from-end.

------

More importantly for this repo in particular, tho, that's a different idea than this proposal, so I'm going to close this as technically off topic. The TC39 Discourse instance is the place to talk about completely new ideas.
